-- Pinacoteca: a gallery-wall colorscheme.
-- Palette and provenance: theme/pinacoteca/colors.toml. Highlights are generated by
-- mini.base16, then adjusted so that identifiers stay in linen, diagnostics are their
-- own family, and surfaces differ from the wall by lightness only.

local ok, base16 = pcall(require, "mini.base16")
if not ok then
  -- On a fresh install lazy.nvim tries the colorscheme before plugins exist.
  vim.notify("pinacoteca: mini.base16 is not installed yet", vim.log.levels.WARN)
  return
end

local p = {
  bg0 = "{{bg0}}",
  bg1 = "{{bg1}}",
  bg2 = "{{bg2}}",
  bg3 = "{{bg3}}",
  comment = "{{comment}}",
  fg_dim = "{{fg_dim}}",
  fg = "{{fg}}",
  fg_bright = "{{fg_bright}}",
  red = "{{red}}",
  orange = "{{orange}}",
  gold = "{{gold}}",
  green = "{{green}}",
  aqua = "{{aqua}}",
  blue = "{{blue}}",
  purple = "{{purple}}",
  red_bg = "{{red_bg:upper}}",
  green_bg = "{{green_bg}}",
  gold_bg = "{{gold_bg:upper}}",
  blue_bg = "{{blue_bg:upper}}",
}

vim.cmd("highlight clear")
vim.o.termguicolors = true
vim.o.background = "dark"

base16.setup({
  palette = {
    base00 = p.bg0,
    base01 = p.bg1,
    base02 = p.bg2,
    base03 = p.comment,
    base04 = p.fg_dim,
    base05 = p.fg,
    base06 = p.fg_bright,
    base07 = p.fg_bright,
    base08 = p.red,
    base09 = p.orange,
    base0A = p.gold,
    base0B = p.green,
    base0C = p.aqua,
    base0D = p.blue,
    base0E = p.purple,
    base0F = p.orange,
  },
  use_cterm = false,
  plugins = { default = true },
})

vim.g.colors_name = "pinacoteca"

local function hl(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

-- Linen: colour marks meaning, not structure.
hl("Identifier", { fg = p.fg })
hl("@variable", { fg = p.fg })
hl("@variable.member", { fg = p.fg })
hl("@variable.parameter", { fg = p.fg })
hl("@variable.builtin", { fg = p.red })
hl("@property", { fg = p.fg })
hl("@lsp.type.variable", {})
hl("@lsp.type.property", {})
hl("@lsp.type.parameter", {})
hl("Delimiter", { fg = p.fg_dim })
hl("@punctuation.bracket", { fg = p.fg_dim })
hl("@punctuation.delimiter", { fg = p.fg_dim })
hl("@punctuation.special", { fg = p.aqua })
hl("Operator", { fg = p.fg_dim })
hl("@operator", { fg = p.fg_dim })
hl("Comment", { fg = p.comment, italic = true })
hl("@comment", { fg = p.comment, italic = true })
hl("Todo", { fg = p.gold, bg = p.gold_bg, bold = true })

-- Pigments by token family.
hl("Keyword", { fg = p.purple })
hl("@keyword", { fg = p.purple })
hl("@keyword.return", { fg = p.purple, italic = true })
hl("Function", { fg = p.blue })
hl("@function", { fg = p.blue })
hl("@function.builtin", { fg = p.blue })
hl("@function.method", { fg = p.blue })
hl("@constructor", { fg = p.gold })
hl("Type", { fg = p.gold })
hl("@type", { fg = p.gold })
hl("@type.builtin", { fg = p.gold })
hl("@module", { fg = p.fg })
hl("String", { fg = p.green })
hl("@string", { fg = p.green })
hl("@string.escape", { fg = p.aqua })
hl("@string.regexp", { fg = p.aqua })
hl("@string.special", { fg = p.aqua })
hl("Character", { fg = p.aqua })
hl("Number", { fg = p.orange })
hl("Boolean", { fg = p.orange })
hl("Constant", { fg = p.orange })
hl("@constant", { fg = p.orange })
hl("@constant.builtin", { fg = p.orange })
hl("@tag", { fg = p.blue })
hl("@tag.attribute", { fg = p.fg })
hl("@tag.delimiter", { fg = p.fg_dim })

-- Diagnostics are their own family.
hl("DiagnosticError", { fg = p.red })
hl("DiagnosticWarn", { fg = p.gold })
hl("DiagnosticInfo", { fg = p.blue })
hl("DiagnosticHint", { fg = p.aqua })
hl("DiagnosticOk", { fg = p.green })
hl("DiagnosticUnderlineError", { sp = p.red, undercurl = true })
hl("DiagnosticUnderlineWarn", { sp = p.gold, undercurl = true })
hl("DiagnosticUnderlineInfo", { sp = p.blue, undercurl = true })
hl("DiagnosticUnderlineHint", { sp = p.aqua, undercurl = true })
hl("DiagnosticVirtualTextError", { fg = p.red, bg = p.red_bg })
hl("DiagnosticVirtualTextWarn", { fg = p.gold, bg = p.gold_bg })
hl("DiagnosticVirtualTextInfo", { fg = p.blue, bg = p.blue_bg })
hl("DiagnosticVirtualTextHint", { fg = p.aqua, bg = p.bg1 })
hl("Error", { fg = p.red })
hl("ErrorMsg", { fg = p.red })
hl("WarningMsg", { fg = p.gold })
hl("MoreMsg", { fg = p.green })
hl("Question", { fg = p.gold })
hl("Title", { fg = p.gold, bold = true })

-- The wall: surfaces differ by lightness only.
hl("Normal", { fg = p.fg, bg = p.bg0 })
hl("NormalNC", { fg = p.fg, bg = p.bg0 })
hl("NormalFloat", { fg = p.fg, bg = p.bg1 })
hl("FloatBorder", { fg = p.bg3, bg = p.bg1 })
hl("FloatTitle", { fg = p.gold, bg = p.bg1, bold = true })
hl("Pmenu", { fg = p.fg, bg = p.bg1 })
hl("PmenuSel", { fg = p.bg0, bg = p.gold, bold = true })
hl("PmenuSbar", { bg = p.bg2 })
hl("PmenuThumb", { bg = p.bg3 })
hl("CursorLine", { bg = p.bg1 })
hl("CursorColumn", { bg = p.bg1 })
hl("ColorColumn", { bg = p.bg1 })
hl("CursorLineNr", { fg = p.gold, bold = true })
hl("LineNr", { fg = p.bg3 })
hl("SignColumn", { bg = "NONE" })
hl("FoldColumn", { fg = p.bg3 })
hl("Folded", { fg = p.fg_dim, bg = p.bg1 })
hl("Visual", { bg = p.bg2 })
hl("VisualNOS", { bg = p.bg2 })
hl("Search", { fg = p.bg0, bg = p.gold })
hl("IncSearch", { fg = p.bg0, bg = p.orange })
hl("CurSearch", { fg = p.bg0, bg = p.orange })
hl("Substitute", { fg = p.bg0, bg = p.red })
hl("MatchParen", { fg = p.gold, bold = true, underline = true })
hl("WinSeparator", { fg = p.bg3 })
hl("VertSplit", { fg = p.bg3 })
hl("StatusLine", { fg = p.fg_dim, bg = p.bg1 })
hl("StatusLineNC", { fg = p.comment, bg = p.bg1 })
hl("TabLine", { fg = p.fg_dim, bg = p.bg1 })
hl("TabLineFill", { bg = p.bg1 })
hl("TabLineSel", { fg = p.bg0, bg = p.gold, bold = true })
hl("WinBar", { fg = p.fg_dim, bg = p.bg0 })
hl("WinBarNC", { fg = p.comment, bg = p.bg0 })
hl("Whitespace", { fg = p.bg3 })
hl("NonText", { fg = p.bg3 })
hl("SpecialKey", { fg = p.bg3 })
hl("EndOfBuffer", { fg = p.bg0 })
hl("Directory", { fg = p.blue })
hl("Cursor", { fg = p.bg0, bg = p.gold })
hl("lCursor", { fg = p.bg0, bg = p.gold })
hl("TermCursor", { fg = p.bg0, bg = p.gold })
hl("QuickFixLine", { bg = p.bg2 })
hl("WildMenu", { fg = p.bg0, bg = p.gold })
hl("SpellBad", { sp = p.red, undercurl = true })
hl("SpellCap", { sp = p.gold, undercurl = true })
hl("SpellLocal", { sp = p.aqua, undercurl = true })
hl("SpellRare", { sp = p.purple, undercurl = true })

-- Diff and git.
hl("DiffAdd", { bg = p.green_bg })
hl("DiffChange", { bg = p.blue_bg })
hl("DiffDelete", { fg = p.red, bg = p.red_bg })
hl("DiffText", { bg = p.gold_bg })
hl("Added", { fg = p.green })
hl("Changed", { fg = p.blue })
hl("Removed", { fg = p.red })
hl("@diff.plus", { fg = p.green })
hl("@diff.delta", { fg = p.blue })
hl("@diff.minus", { fg = p.red })
hl("GitSignsAdd", { fg = p.green })
hl("GitSignsChange", { fg = p.blue })
hl("GitSignsDelete", { fg = p.red })

-- LSP and plugin surfaces.
hl("LspInlayHint", { fg = p.comment, bg = p.bg1, italic = true })
hl("LspReferenceText", { bg = p.bg2 })
hl("LspReferenceRead", { bg = p.bg2 })
hl("LspReferenceWrite", { bg = p.bg2, underline = true })
hl("LspCodeLens", { fg = p.comment, italic = true })
hl("LspSignatureActiveParameter", { fg = p.gold, bold = true })
hl("SnacksIndent", { fg = p.bg2 })
hl("SnacksIndentScope", { fg = p.bg3 })
hl("IblIndent", { fg = p.bg2 })
hl("IblScope", { fg = p.bg3 })
hl("NotifyBackground", { bg = p.bg1 })
hl("WhichKeyBorder", { fg = p.bg3, bg = p.bg1 })
hl("TelescopeBorder", { fg = p.bg3, bg = p.bg1 })
hl("TelescopeNormal", { fg = p.fg, bg = p.bg1 })
hl("TelescopeSelection", { fg = p.fg_bright, bg = p.bg2 })
hl("TelescopeMatching", { fg = p.gold, bold = true })
hl("BlinkCmpMenu", { fg = p.fg, bg = p.bg1 })
hl("BlinkCmpMenuBorder", { fg = p.bg3, bg = p.bg1 })
hl("BlinkCmpMenuSelection", { fg = p.fg_bright, bg = p.bg2 })
hl("BlinkCmpLabelMatch", { fg = p.gold, bold = true })
hl("BlinkCmpDoc", { fg = p.fg, bg = p.bg1 })
hl("BlinkCmpDocBorder", { fg = p.bg3, bg = p.bg1 })

-- Markup.
hl("@markup.heading", { fg = p.gold, bold = true })
hl("@markup.heading.1.markdown", { fg = p.gold, bold = true })
hl("@markup.heading.2.markdown", { fg = p.orange, bold = true })
hl("@markup.heading.3.markdown", { fg = p.blue, bold = true })
hl("@markup.strong", { bold = true })
hl("@markup.italic", { italic = true })
hl("@markup.link", { fg = p.blue })
hl("@markup.link.url", { fg = p.blue, underline = true })
hl("@markup.link.label", { fg = p.aqua })
hl("@markup.raw", { fg = p.aqua })
hl("@markup.raw.block", { fg = p.fg })
hl("@markup.quote", { fg = p.fg_dim, italic = true })
hl("@markup.list", { fg = p.gold })

-- Terminal.
local terminal = {
  p.bg2,
  p.red,
  p.green,
  p.gold,
  p.blue,
  p.purple,
  p.aqua,
  p.fg,
  p.comment,
  p.red,
  p.green,
  p.gold,
  p.blue,
  p.purple,
  p.aqua,
  p.fg_bright,
}
for i, color in ipairs(terminal) do
  vim.g["terminal_color_" .. (i - 1)] = color
end
